### ISSUE TITLE
Atskaitomybės ir sąskaitų plano šablonai

### ISSUE THREAD

**Issue by elektrinis** [Apskaita5/Apskaita5#6]
Dokumentacijoje nurodyta, kad šablonai yra instaliacijos vietoje, tačiau failų su tokiais plėtiniais nerandu nei instaliacijoje, nei portable archyve.
https://github.com/Apskaita5/Apskaita5/wiki/Instaliacija

**Comment by Apskaita5** [comment]
Instaliacijos vietoje yra zipas, jame šablonai.
